name: Linux tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linux:
    name: Linux Py${{ matrix.PYTHON_VERSION }} ${{ matrix.SPYDER_SOURCE }}
    runs-on: ubuntu-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'ubuntu'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.8', '3.9', '3.10']
        SPYDER_SOURCE: ['conda', 'git']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install System Packages
        run: | 
          sudo apt-get update --fix-missing
          sudo apt-get install -qq pyqt5-dev-tools libxcb-xinerama0 xterm --fix-missing
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           channels: conda-forge
           auto-update-conda: true
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Checkout Spyder from git
        if: matrix.SPYDER_SOURCE == 'git'
        uses: actions/checkout@v3
        with:
          repository: 'spyder-ide/spyder'
          path: 'spyder'
      - name: Install Spyder's dependencies
        if: matrix.SPYDER_SOURCE == 'git'
        shell: bash -l {0}
        run: |
          conda env update --file spyder/requirements/main.yml -q
          conda env update --file spyder/requirements/linux.yml -q
      - name: Install Spyder from source
        if: matrix.SPYDER_SOURCE == 'git'
        shell: bash -l {0}
        run: pip install --no-deps -e spyder
      - name: Install plugin dependencies
        shell: bash -l {0}
        run: conda install --file requirements/conda.txt -y -q
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          conda install nomkl -y -q
          conda install --file requirements/tests.txt -y -q
      - name: Install plugin
        shell: bash -l {0}
        run: pip install --no-deps -e .
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: xvfb-run --auto-servernum pytest spyder_unittest --cov=spyder_unittest -x -vv
        timeout-minutes: 10
      - name: Upload coverage to Codecov
        if: matrix.PYTHON_VERSION == '3.10'
        shell: bash -l {0}
        run: codecov -t 3458851b-c7a5-4108-be5e-9d19066a2fde
